### ISSUE TITLE
As a new player I would like to be able to set passwords

### ISSUE THREAD

**Issue by raimz27** [cultris-community/back-end-user-stories#24]
It's really annoying to have players that are decent or good at the game join and destroy us even though we name the room ''please don't join'' there are still people that join :/

**Comment by kb1900** [comment]
Hi there - I don’t mean this in any bad way but this is already a feature and I think it couldn’t really be implemented in any better way. 

On the settings page the room creator sees two tick boxes. The first is to auto start rounds and the second is to auto join players.

So next time you can just untick autojoin plauers and assign slots to those you actually want to play with you
